### ISSUE TITLE
implement if/elif*/else

### ISSUE THREAD

**Issue by gilch** [gilch/hebigo#9]
How should these look in Hegibo?
Given the Python examples,
```python
if a < b:
    print('less')
    return a  # Assume we're in a function.
elif a > b:
    print('more')
    return b
elif a == b:
    print('equal')
    return a
else:
    print 'nan'
```
and
```python
if case == x:
    print(x, a)
else:
    print(b)
```
Naiively, one might think
```
if: (case == x)
    print: x, a
else:
    print: b
```
This is gramatically valid Hebigo, but then the implied brackets would look like this
```
{if: (case == x)
    {print: x, a}}
{else:
    {print: b}}
```
The `if` and `else` are completely separate forms. Not going to work. They need a surrounding form.

**Comment by gilch** [comment]
Option 1, add a surrounding `cond:`
```
cond:
    if: (case == x)
        print: x, a
    else:
        print: b
```
The inside looks very Pythonic, but we seem to have added an extra indent and reserved word compared to the Python for no reason.

Option 2, use control words.
```
if: (a<b)
    print: "less"
    a
    :elif (a>b)
    print: "more"
    b
    :elif (a==b)
    print: "equal"
    a
    :else
    print: "nan"
````
But now the conditions are a bit difficult to distinguish from their blocks. Good layout is not well-enforced. Parsing this into subtuples takes some extra work and those subtuples might have been good visual cues in the first place.

Option 3, no control words or subtuples
```
    if: (a<b) print: "less"
        (a>b) print: "more"
        (a==b) print: "equal"
        :else print: "nan"  # Non-empty strings like ":else" are truthy. It's not a special case.
```
This is like Clojure's `cond`. But we lose the implied `progn/begin/do`.
In the functional style, we mostly don't use the implied progn anyway.
Were I designing a language from scratch this would be attractive,
but we're trying to feel familiar to Pythonistas for Hebigo's basic macros.
For a fair comparison, we have to include that.
```
if: (a<b)
    begin:
        print: "less"
        a
    (a>b)
    begin:
        print: "more"
        b
    (a==b)
    begin:
        print: "equal"
    :else print: "nan"
```
This actually doesn't look bad to me, even with the explicit "begin:", but it's not Pythonic.

Option 4, subtuples like `cond`.
```
if:
    :: (a<b)
        print: "less"
        a
    :: (a>b)
        print: "more"
        b
    :: (a==b)
        print: "equal"
        a
    :: :else
        print: "nan"
```
I don't like using empty hotwords if I can avoid them. That first line looks pretty empty. Structurally, this is just like Option 1, but maybe less readable.

Option 5, less empty
```
if: 
    :: (a<b)
        print: "less"
        a
    elif: (a>b)
        print: "more"
        b
    elif: (a==b)
        print: "equal"
        a
    else:
        print: "nan"
```
Same structure as Options 1 and 4. It uses the word `if` instead of `cond`, but then the first one still has to be empty.

Option 6, no empty.
```
if: (a<b)
    print: "less"
    elif: (a>b)
        print: "more"
    elif: (a==b)
        print: "equal"
    else:
        print: "nan"
```
The indent looks wrong here.

Option 7, empty hotword after the first condition.
```
if: (a<b)
    ::
        print: "less"
    elif: (a>b)
        print: "more"
    elif: (a==b)
        print: "equal"
    else:
        print: "nan"
```
The indents look right, except perhaps for the first condition, which aren't aligned between `if` and `elif` in Python anyway. This is also a lot closer to how it actually has to be compiled. The first condition doesn't need to be a thunk, since it always gets evaluated.

A more compact form still works.
```
if: (case==x) :: print: x a
    else: print: b
```

**Comment by gilch** [comment]
I've actually already implemented Option 7, but thought I'd document how I came up with it. I'm still considering alternatives though.

**Comment by gilch** [comment]
Option 8, `then` clause
```
if: (a<b)
    then:
        print: "less"
    elif: (a>b)
        print: "more"
    elif: (a==b)
        print: "equal"
    else:
        print: "nan"
```
Almost exactly the same structure as Option 7, but without the empty hotword. This reads better to me.

Compact forms
```
if: (case==x) then: print: x a
    else: print: b
```
```
if: (case==x)
    then: print: x a
    else: print: b
```

Unfortunately, `then` is not a reserved word. We can special-case it in that position in the `if:` macro, but it might still get qualified in a `!mask`. The `if:` macro could simply ignore the qualification though.
